<?php

namespace WebsiteBundle\Repository;

use Doctrine\DBAL\DBALException;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends \Doctrine\ORM\EntityRepository
{

    public function getSubcategories()
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql = "select c.id, (SELECT concat(cat.name,' - ', c.name)) as subcategory from categories as c
                INNER JOIN categories as cat on c.parent_id = cat.id";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
            echo $e->getMessage();
        }
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
