<?php

namespace WebsiteBundle\Repository;

use Doctrine\DBAL\DBALException;

/**
 * Orders_ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Orders_ItemsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getBestTen()
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = "SELECT product_id, SUM(quantity) AS ItemCount
                FROM orders__items
                GROUP BY product_id
                ORDER BY SUM(quantity) DESC LIMIT 10;";
        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }

        $stmt->execute();
        return $stmt->fetchAll();
    }
}
