<?php

namespace WebsiteBundle\Repository;

use Doctrine\DBAL\DBALException;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{

}
